version: '2'

services:
    php:
        build: ./${PHP_VERSION}
        container_name: php
        volumes:
            - ./logs/php:/var/log/php
            - ${SITE_PATH}:/var/www/bitrix
        environment:
              PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - '${INTERFACE}:9000:9000'
        links:
            - mariadb
        restart: always
    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: webserver
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ${SITE_PATH}:/var/www/bitrix
        ports:
            - '${INTERFACE}:80:80'
            - '${INTERFACE}:81:81'
            - '${INTERFACE}:443:443'
        links:
            - php
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mariadb:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mariadb:
        image: "mariadb:10.1.38"
        restart: "on-failure:5"
        ports:
            - '${INTERFACE}:3307:3307'
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./logs/mysql:/var/log/mysql
            - ./data/mysql:/var/lib/mysql
            - ./mysql/db.cnf:/etc/mysql/conf.d/db.cnf